### ISSUE TITLE
Add telephone missing icon

### ISSUE THREAD

**Issue by fmquaglia** [cobolab/ionicon#2]
@mahdaen I am trying to add some icons that are missing currently in this module.
E.G.: ```ion-ios-telephone``` (```&#xf4b9;``` in Ionicons v2.0.0)
![telephone](http://d.pr/i/rvRn+)
See [here](https://github.com/driftyco/ionicons/blob/master/css/ionicons.css#L1008)

I tried adding the icon key ```telephone``` (value=0xf429) to the ```maps``` variable.
Unfortunately that didn't work. I tried a coup`le of other things too with no luck.

I am willing to help adding as many missing icons as I can if you explain me the logic you're using.

PS: your module is being of great help in one of my current projects. Thanks!

**Comment by mahdaen** [comment]
Hey @fmquaglia, to update the icons to v2 you need to replace the icons inside the `font` folder and change the maps since the character codes is different. E.g: The icon `drag` was changed from `\e0b1` to `\f130`, and the icon `arrow-left` was removed and changed to `arrow-left-a, ...`.

Btw, I can't upgrade it since it'll break some projects that using it. I can't remember which projects but some of them using the latest version pattern, so releasing new version will break them.

If you want, I can create `angularic-ionicon-2` so you can using it. ;)

**Comment by fmquaglia** [comment]
Thanks a lot @mahdaen 
I'll do so making clear attribution to you and this project of course.
Do you mind if I reach to you while developing ```angularic-ionicon-2``` if I have a question or problem?
I would appreciate it a lot.

**Comment by mahdaen** [comment]
Sure, just ping me if you need any help. ;)

Btw, do you want me to develop the `angularic-ionicon-2` or you want to do it?

**Comment by fmquaglia** [comment]
Thanks a lot!
Yes, please create the project and add me as collaborator, since you're the author of the original project.
